---
name: config-server-forge

instance_groups:
- name: config-server-forge
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
   - name: config-server-blacksmith-plans


variables: []

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false


releases:
  - name:    containers
    version: 1.3.1
    url:     https://github.com/jhunt/containers-boshrelease/releases/download/v1.3.1/containers-1.3.1.tgz
    sha1:    ec6945e71aff8d6e7d37f425702713f3ad9227a5
