#!/bin/bash
set -eu

DATADIR="${DATADIR:-/var/vcap/jobs/config-server-blacksmith-plans/plans/standard/data}"
CREDENTIALS=${CREDENTIALS:-"secret/test"}
BLACKSMITH_WORKDIR="${WORKDIR:-/tmp}"
TMPDIR="${TMPDIR:-/tmp}"
RAWJSONFILE="${RAWJSONFILE:-/tmp/rawjsonfile}"
YAMLFILE="${YAMLFILE:-/tmp/yamlfile}"
TEMPLATEFILE="${TEMPLATEFILE:-${TMPDIR}/template.$$.yml}"
APPLICATIONFILE="${APPLICATIONFILE:-${TMPDIR}/application.$$.yml}"
WRAPPERFILE="${WRAPPERFILE:-${TMPDIR}/wrapper.$$.yml}"
DATADIR="${DATADIR:-data}"
CFGSVRDIR="${DATADIR}/cfgsvr"
NGINXDIR="${DATADIR}/nginx"

# /var/vcap/jobs/config-server-blacksmith-plans/plans/standard/data/nginx/nginx.conf
# /var/vcap/data/blacksmith/config-server-forge/services/standard/data/nginx/certs/cfgsvr.local.crt

# There is a bug spruce if I specify a full file path, that is somehow treats the filename differently
# using SPRUCE_FILE_BASE_PATH to get around the error
# Saw this error in spruce - Version 1.25.2
# echo basename ${YAMLFILE##*/} # basename
# echo dirname ${YAMLFILE%/*} # dirname

gen_application_template() {
cat <<-EOF >| "${TEMPLATEFILE}"
meta:
  (( load "${YAMLFILE##*/}" ))
info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          (( grab meta.git ))
  banner:
    location: "file:/var/vcap/data/blacksmith/banner.txt"
  main:
    banner-mode: console  # values off console log
management:
  context_path: /admin
EOF
}

gen_application_template
SPRUCE_FILE_BASE_PATH=${YAMLFILE%/*}  spruce merge -m  --prune meta "${TEMPLATEFILE}" >| "${APPLICATIONFILE}"


# Do these names need to stay at username password instead of client_* names?
safe gen -l 16 ${CREDENTIALS}/config username
safe gen       ${CREDENTIALS}/config password
safe fmt crypt-sha512 ${CREDENTIALS}/config password nginx_password
echo "$(safe get ${CREDENTIALS}/config:username):$(safe get ${CREDENTIALS}/config:nginx_password)" > ${NGINXDIR}/nginx.passwd

safe set ${CREDENTIALS}/config "docker_compose_yml@${DATADIR}/docker-compose.yml"
safe set ${CREDENTIALS}/config/cfgsvr "application_yml@${APPLICATIONFILE}"
safe set ${CREDENTIALS}/config/cfgsvr "banner_txt@${CFGSVRDIR}/banner.txt"
safe set ${CREDENTIALS}/config/nginx "nginx.passwd@${NGINXDIR}/nginx.passwd"
safe set ${CREDENTIALS}/config/nginx "nginx_conf@${NGINXDIR}/nginx.conf"
safe set ${CREDENTIALS}/config/nginx "dhparam_pem@${NGINXDIR}/dhparam/dhparam.pem"
safe set ${CREDENTIALS}/config/nginx "public_key@${NGINXDIR}/certs/cfgsvr.local.crt"
safe set ${CREDENTIALS}/config/nginx "private_key@${NGINXDIR}/certs/cfgsvr.local.key"

[[ -z "${BLACKSMITH_DEBUG-}" ]] && {
  rm -f "${TEMPLATEFILE}" "${APPLICATIONFILE}" "${NGINXDIR}/nginx.passwd"
}

exit 0
